### ISSUE TITLE
Use externalized configuration to define service broker catalog

### ISSUE THREAD

**Issue by s-bortolussi** [spring-cloud/spring-cloud-open-service-broker#11]
For catalog management, spring-boot-cf-service-broker provides a default implementation that requires the broker to just provide an implementation of a [Catalog bean](https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker/blob/master/src/main/java/org/springframework/cloud/servicebroker/model/Catalog.java). 
An improvement would be to enable the use of [externalized configuration](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html) (properties files, YAML files, environment variables or command-line arguments) to set Catalog bean attributes.

Then, a very basic catalog definition using env variables would be :

```
$ export SERVICES_DEFINITIONS[MONGO_DB]_ID=mongodb-service-broker 
$ export SERVICES_DEFINITIONS[MONGO_DB]_NAME=Mongo DB
$ export SERVICES_DEFINITIONS[MONGO_DB]_DESCRIPTION=A simple MongoDB service broker implementation
$ export SERVICES_DEFINITIONS[MONGO_DB]_PLANS[DEFAULT]_ID=mongo-plan
$ export SERVICES_DEFINITIONS[MONGO_DB]_PLANS[DEFAULT]_NAME=Default Mongo Plan
$ export SERVICES_DEFINITIONS[MONGO_DB]_PLANS[DEFAULT]_DESCRIPTION=This is a default mongo plan. All services are created equally
```

This feature can be extended by enabling a [remote externalized configuration](https://github.com/spring-cloud/spring-cloud-config)

**Comment by scottfrederick** [comment]
@s-bortolussi I agree this would be a nice feature to have. I've played a bit with defining catalog metadata in YAML, since it seems like a good fit for the structure. The use cases I've had made static definition difficult, as some elements of the catalog metadata could only be known at runtime, but I think it is worth exploring this for simpler use cases. 

I'm not sure about making this project dependent on Spring Cloud Config though. I'll have to think about the implications of pulling that in as a dependency.
