### ISSUE TITLE
Mandatory service_id and plan_id for last_operation requests in 1.0.3

### ISSUE THREAD

**Issue by thomasjanke** [spring-cloud/spring-cloud-open-service-broker#117]
Hi,

it seems that 1.0.3 enforces service_id and plan_id as mandatory request parameters for last_operation requests. In the OpenServiceBroker API Spec 2.13 they are optional, though. Is that done on purpose? Am I missing something?

Best,
Thomas

**Comment by AlbertoImpl** [comment]
Hi @thomasjanke, Thanks for reaching out!
Looks like `1.0.3.RELEASE` was based on the OpenServiceBroker API Spec version 2.11 where `last_operation` had those parameters as mandatory: https://github.com/openservicebrokerapi/servicebroker/blob/v2.11/spec.md#polling-last-operation

https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/1.0.3.RELEASE/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.java#L101-L104


On the latest `2.0.1.RELEASE` version, the issue was addressed and it should be compatible with the latest Spec version: 
https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/2.0.1.RELEASE/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.java#L149-L150

Is there anything stopping you from upgrading?

Thanks,
Alberto

**Comment by AlbertoImpl** [comment]
Good catch! You are completely right @thomasjanke. Those parameters were optional, just the way it was described changed and it was missed.

I understand that upgrading to boot `2.x` is a major change, so we will release a new `1.0.x` version with this fixed.

As a note, Spring Boot `1.x` EOL is in less than a year now: https://spring.io/blog/2018/07/30/spring-boot-1-x-eol-aug-1st-2019

Thanks again!
Alberto

**Comment by thomasjanke** [comment]
> so we will release a new 1.0.x version with this fixed.
Great. Thanks a lot!

**Comment by royclarkson** [comment]
This was resolved in #118
