### ISSUE TITLE
Incorrect HTTP Response code when the X-Broker-API-Version header doesn't exist

### ISSUE THREAD

**Issue by aukhatov** [spring-cloud/spring-cloud-open-service-broker#217]
Hi guys!
According to the OSB spec v2.14 https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#api-version-header the `X-Broker-API-Version` header is mandatory. It means when any mandatory data is missing service broker must return `400 Bad Request`.

But current implementation in  a method `ApiVersionInterceptor#preHandle` checks only version is equal or not to which implemented by service broker.

**Comment by scottfrederick** [comment]
I think we need to be careful here. I'm not sure what version of the spec made this header mandatory (it appears it has been marked mandatory for at least a few years). While the spec does state that the platform MUST send the `X-Broker-API-Version` header, older versions of platforms might not adhere to the spec. Changing this project to return an HTTP error code when the header is missing might cause brokers to fail when running with these older platform versions where they did not fail before. 

The code currently **will not** look for the `X-Broker-API-Version` header by default, because the default expected version is `*`.  In this case, I don't see value in making a change that results in an HTTP error when the header is missing, given that the broker has not expressed an interest in validating the version. 

The code **will** check for the header if the broker author specifies a version via the `spring.cloud.openservicebroker.api-version` property or a `BrokerApiVersion` bean. A missing header or a value that doesn't match the expected version will result in a `412 PRECONDITION FAILED`. It does seem reasonable to me to return a different code like `400 BAD REQUEST` if the header is missing.

**Comment by royclarkson** [comment]
I agree with @scottfrederick. We should change the response to a 400, so it's compliant with the spec, but unless the service broker has been configured to check for the version, I prefer not to require the header.

**Comment by aukhatov** [comment]
@scottfrederick @royclarkson thanks for your replies, it was very quickly.

**Comment by aukhatov** [comment]
Anyway I created the issue https://github.com/openservicebrokerapi/servicebroker/issues/673 about the problem.

**Comment by royclarkson** [comment]
Closed in dcce56b32affb70c7efaeeaa3d8a127557dd8ea9 and b6a571f9b82fdcdd0fb781f4ba34ccd862683d69.
