### ISSUE TITLE
Wrong HTTP response code when service instance provisioning is in progress

### ISSUE THREAD

**Issue by bytestack** [spring-cloud/spring-cloud-open-service-broker#244]
According to the OSBAPI [specification v2.14](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#response-3) a service broker MUST return a HTTP 202 when a service instance is beeing provisioned and another PUT is sent with the same instance id:

> 202 Accepted MUST be returned if the Service Instance provisioning is in progress. [...].

The class `ServiceBrokerExceptionHandler ` returns a 404 instead:

https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/1affa60be338773b13771409f7b7f92d44a08b32/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceBrokerExceptionHandler.java#L153

**Comment by royclarkson** [comment]
Thanks for reporting

**Comment by royclarkson** [comment]
We're currently using the `ServiceBrokerOperationInProgressException` for the situation where a service instance or service instance binding is requested while a previous operation is still in progress. In that scenario it is correct to return a `404` as seen in the [spec](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#response-4).

We don't currently have any tests validating that repeating a `PUT` should return a `202` as described in this issue. We should consider a new exception for this scenario instead of modifying the existing one.
