### ISSUE TITLE
Document request path prefix

### ISSUE THREAD

**Issue by ivanangelov** [spring-cloud/spring-cloud-open-service-broker#271]
If there is a single word at the beginning of the path prefix it seems to be ignored.

For example:
```
curl https://username:password@service-broker-url/v2/catalog 
```
and
```
curl https://username:password@service-broker-url/<some_word>/v2/catalog 
```

both internally map to **/v2/catalog** and return the service catalog.
The Maven version of the API we use is: **2.1.1.RELEASE**

Is this the expected behaviour?

**Comment by scottfrederick** [comment]
This is the expected behavior. 

The path prefix is not ignored, it is provided to the service broker application in the [`platformInstanceId` field of all request objects](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/model/ServiceBrokerRequest.java#L75).  This allows a service broker to detect the identity of a platform that it has been registered to, as described in the [CF docs](https://docs.cloudfoundry.org/services/supporting-multiple-cf-instances.html#routing-auth). 

For example, if an operator registered a service broker to one CF platform instance with 
```
$ cf create-service-broker mybroker username password https://mybroker.example.com/east
```

and registered the same service broker to another CF platform instance with 
```
$ cf create-service-broker mybroker username password https://mybroker.example.com/west
```

Then the broker could expect requests to the paths `https://username:password@mybroker.example.com/east/v2/catalog` and `https://username:password@mybroker.example.com/west/v2/catalog`, with the `platformInstanceId` field in request objects containing the value `east` or `west`. 

It doesn't look like this feature is mentioned in the project documentation anywhere. It might be good to change that.

**Comment by ivanangelov** [comment]
Thanks for your response! 
Yes, I suppose it would be nice to include it in the project documentation as well.

**Comment by royclarkson** [comment]
I added @scottfrederick's great example to the docs.
