### ISSUE TITLE
Allow the platform to supply Service ID and Plan ID as hints when retrieving a service binding or a service instance

### ISSUE THREAD

**Issue by JamesMcQiuggan** [spring-cloud/spring-cloud-open-service-broker#287]
as per OSB API spec getting a service instance is supposed to allow the use of "service_id" and "plan_id" to give brokers a hint as to the context of the UUID they are being asked to fetch:

[see here](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#fetching-a-service-instance)

Spring OSB does not seem to support this, neither `getServiceInstance` in `ServiceInstanceController` or the `GetServiceInstanceRequest` object support these query parameters.

This would be useful if your broker served multiple catalog items/service definitions and your service instance ID does not indicate which offering it represents, and you are storing each of your service definitions in a different back-end store leading to having to search each in turn to see if the UUID matches.

**Comment by royclarkson** [comment]
Thanks for the feedback. That feature is new since [v2.15](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#fetching-a-service-instance) of the spec, which is what the latest release of Spring Cloud Open Service Broker supports. We'll be adding support for v2.16 in an upcoming release.

**Comment by royclarkson** [comment]
Let's keep it open to track the OSBAPI 2.16 update.
