### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by Fitzoh** [spring-cloud/spring-cloud-open-service-broker#41]
The cloud foundry service broker API has been standardized into the [Open Service Broker API](https://openservicebrokerapi.org/).
Should the project name/documentation be updated to reflect that it can be used with more than just CF?

**Comment by scottfrederick** [comment]
Yes, we'll want to do that at some point. Luckily there are very few places in the code (aside from comments) that use "Cloud Foundry", so such a change won't have much impact on client app compatibility. The project coordinates will need to change since the artifact ID is currently `spring-cloud-cloudfoundry-service-broker`. There are some proposed changes that could drive the next minor release (i.e. `1.1.0`), and that might be a good time to make the change.

**Comment by royclarkson** [comment]
How is `spring-cloud-open-service-broker`?

**Comment by scottfrederick** [comment]
I like `spring-cloud-open-service-broker` for the project name. It matches the name of the core subproject and artifact, and the common prefix of the Boot starter artifact names.

**Comment by cah-andrewfitzgerald** [comment]
:shipit:

**Comment by royclarkson** [comment]
done
