### ISSUE TITLE
Missing exception/handler for '410 Gone' response

### ISSUE THREAD

**Issue by artkoshelev** [spring-cloud/spring-cloud-open-service-broker#87]
According to OSB spec, 410 Gone response could be returned when calling:
* `ServiceInstanceService.deleteServiceInstance()`
* `ServiceInstanceService.getLastOperation()`
* `ServiceInstanceBindingService.deleteServiceInstanceBinding()`

However there is no code to produce this error in a core package

**Comment by royclarkson** [comment]
Hi thanks for reporting! I believe we have these cases covered already. If you are not seeing the expected behavior, then please let us know.

- [delete service instance](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.java#L216)
- [get last operation](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.java#L177)
- [delete service binding](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceInstanceBindingController.java#L162)

**Comment by artkoshelev** [comment]
Yep, i see now. It's just not consistent with the rest of code where we have exceptions and corresponding handlers. What do you think?

**Comment by artkoshelev** [comment]
And actual return code for delete service instance is 422 instead of 410 because of exception handler executed first and catch block in ServiceController never reached.

**Comment by scottfrederick** [comment]
@artkoshelev From the OSB API spec [section on error handling](https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#broker-errors): 

> Broker failures beyond the scope of the well-defined HTTP response codes listed above (like 410 Gone on Deprovisioning) MUST return an appropriate HTTP response code (chosen to accurately reflect the nature of the failure) and a body containing a valid JSON Object (not an array).

All of the `@ExceptionHandler` methods build a response with a `description` element in the body of the response, containing the details of the error as suggested in the spec. 

The `410 Gone` responses aren't technically errors (i.e. they aren't unexpected), and are returned with an empty response body. This is why they aren't handled in `@ExceptionHandler` methods.

**Comment by artkoshelev** [comment]
Ok, thanks for clarifications!
